services:
  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "4000:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    image: stats-server
    container_name: stats-server
    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: jdbc:postgresql://stats-db:5432/stats
      DATABASE_USER_NAME: dbuser
      DATABASE_PASSWORD: 12345

  ewm-service:
    image: ewm-service
    container_name: ewm-service
    ports:
      - "9090:8080"
